### ISSUE TITLE
META.yml lists test deps as build_requires

### ISSUE THREAD

**Issue by dolmen** [kentnl/Dist-Zilla-Util-ConfigDumper#2]
In release 0.003006, [META.yml](https://metacpan.org/source/KENTNL/Dist-Zilla-Util-ConfigDumper-0.003006/META.yml#L5) lists many dzil plugins as `build_requires`. It seems that `test_requires` has been merged in `build_requires`.
META.json which is META v2 is ok.

**Comment by kentfredric** [comment]
Yeah. Though that seems to be a consequence of the fact META.yml is only meta v1.4 , and thus prereqs are merged into `build_requires` instead.  I don't know how I'm supposed to avoid that, as far as `META.yml` is concerned, it is "right".

( That is to say, it is CPAN::Meta that is converting `test_requires` into `build_requires` )

**Comment by dolmen** [comment]
> as far as META.yml is concerned, it is "right".

Well, unfortunately, I agree.
I can't use CPAN.pm `build_requires_install_policy=yes` until JSON is installed, as some dependencies are not installed at the end. But this is more a CPAN.pm bug.
