### ISSUE TITLE
Please provide a more descriptive module/distribution description

### ISSUE THREAD

**Issue by xtaran** [kentnl/Dist-Zilla-Util-ConfigDumper#3]
"Easy implementation of 'dumpconfig'" doesn't really tell much about the module or distribution. What is it used for, in which cases do you need it?

Please provide at least one paragraph describing the module's purpose or use cases.

Background for this request is that I want to package Dist::Zilla::Plugin::MetaProvides for Debian and it depends on Dist::Zilla::Util::ConfigDumper, so I need to package that one, too. And a package needs a proper package description. "Easy implementation of 'dumpconfig'" is definitely no proper package description and far too short. But unfortunately neither the README nor the POD contain a proper description of this module/distribution.

**Comment by kentfredric** [comment]
I don't know how to word it more clearly without being overly burdensome and wordy.

"dumpconfig" is a specific function name in Dist::Zilla which returns metadata about a plugins configuration for the purpose of reporting it to an output target, and this module simplifies collection of state from the plugin for reporting to that function name.

I'll gladly create a better ABSTRACT if you have some better suggestions :)

I will also see if I can bolt together a nice DESCRIPTION section some time today.

Thanks for the bug =)

**Comment by xtaran** [comment]
Hi,

On Thu, Jul 30, 2015 at 08:12:38PM -0700, Kent Fredric wrote:
> I don't know how to word it more clearly without being overly burdensome and wordy.

Wordy may not be that bad. :-)

> [...] which returns metadata about a plugins configuration for the
> purpose of reporting it to an output target, and this module
> simplifies collection of state from the plugin for reporting to that
> function name.

This sounds like a already good start for a more verbose description.

> I'll gladly create a better ABSTRACT if you have some better
> suggestions :)

My try so far (but mostly made up out of thin air) is:

Short description:

Dist::Zilla helper utility to dump configurations

"Long" description:

Dist::Zilla::Util::ConfigDumper provides functions for extracting the
plugin configuration data with Dist::Zilla's "around dump_config".

But already now I like your sentence quoted above better. :-)

		Kind regards, Axel

**Comment by kentfredric** [comment]
I thought really hard and found a good medium: 
```
# ABSTRACT: A Dist::Zilla plugin configuration extraction utility.
```
Its a mouthful, but its concise.

:)

**Comment by kentfredric** [comment]
Shipped: https://metacpan.org/release/KENTNL/Dist-Zilla-Util-ConfigDumper-0.003007#whatsnew 

If you have any further queries/enhancements, feel free to open another bug :)

Thanks.
